Repository segeeslice/cc-final-project, pull requests merged in 2021-04, with the labels that each got.

#4 Move facial recognition video into own component
  react-app/src/App.jsx
  react-app/src/components/FaceRecVideo.jsx
Labels: refactor

#5 Start stop face rec
  react-app/src/App.jsx
  react-app/src/components/FaceRecVideo.jsx
  react-app/src/components/FaceRecVideoPlayer.jsx
Labels: enhancement

#6 Add loading indicators
  react-app/src/components/FaceRecLoadingOverlay.jsx
  react-app/src/components/FaceRecVideo.jsx
  react-app/src/components/FaceRecVideoPlayer.jsx
Labels: enhancement

#7 Fix up meta info to be more accurate
  react-app/public/favicon.ico
  react-app/public/index.html
  react-app/public/logo192.png
  react-app/public/logo512.png
Labels: bug

#13 Fix issue with buttons not being pressable in Chrome
  react-app/src/components/FaceRecVideoPlayer.jsx
Labels: bug

#14 Utilize Material UI in our web app
  react-app/package-lock.json
  react-app/package.json
  react-app/public/index.html
  react-app/src/App.jsx
  react-app/src/components/FaceRecLoadingOverlay.jsx
  react-app/src/components/FaceRecVideo.jsx
  react-app/src/components/FaceRecVideoPlayer.jsx
  react-app/src/index.js
Labels: enhancement

#15 Image save and integration with reference images
  react-app/package-lock.json
  react-app/package.json
  react-app/public/images/Dustin.jpg
  react-app/public/images/Mo.png
  react-app/public/images/Seg.png
  react-app/src/async-interval.js
  react-app/src/components/FaceRecVideo.jsx
  react-app/src/components/FaceRecVideoPlayer.jsx
  react-app/src/components/PhotoManager.jsx
  react-app/src/components/UploadManager.jsx
  react-app/src/face-rec.js
Labels: enhancement

#17 Splash page
  react-app/src/App.jsx
  react-app/src/components/FaceRecVideoPlayer.jsx
  react-app/src/components/InfoDialog.jsx
  react-app/src/components/PhotoManager.jsx
  react-app/src/components/UploadManager.jsx
  react-app/src/face-rec.js
Labels: enhancement
